name: build_docker_images.yml

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Choose a branch"
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: [self-hosted, label-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure Java/Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Listar contenido de target/
        run: |
          echo "PWD: $(pwd)"
          ls -l target/

      - name: Prepare Dockerfile
        run: |
          cat > Dockerfile <<EOF
          FROM eclipse-temurin:18-jre
          COPY target/*.jar /app/app.jar
          WORKDIR /app
          ENTRYPOINT ["java","-jar","/app/app.jar"]
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mydockerhubuser/myapp:${{ github.event.inputs.branch }}
