name: build_docker_images.yml

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Choose a branch"
        required: true
        default: 'main'

jobs:
  buildMyProjectAtDocker:
    runs-on:
      - self-hosted
      - label-1
    outputs:
      jar-name: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure Java/Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: listar target
        run: |
          echo "PWD: $(pwd)"
          ls -l target/