name: build_docker_images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Elige una rama"
        required: true
        default: "main"

jobs:
  build-and-push:
    runs-on: [self-hosted, label-1]
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Java/Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B package --file pom.xml

      - name: Prepare Dockerfile
        run: |
          cat > Dockerfile <<EOF
          FROM eclipse-temurin:18-jre
          COPY target/*.jar /app/app.jar
          WORKDIR /app
          ENTRYPOINT ["java","-jar","/app/app.jar"]
          EOF

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          driver: docker-container
          endpoint: tcp://docker:2375

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          TAG=${{ github.event.inputs.branch }}
          docker build -t mydockerhubuser/myapp:${TAG} .
          docker push mydockerhubuser/myapp:${TAG}