name: build_docker_images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Elige una rama"
        required: true
        default: "main"

jobs:
  build-and-push:
    runs-on: [self-hosted, label-1]
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configurar Java/Maven
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "18"
          cache: "maven"

      - name: Compilar con Maven
        run: mvn -B package --file pom.xml

      - name: Mostrar artefactos
        run: |
          echo "PWD: $(pwd)"
          ls -l target/

      - name: Crear Dockerfile
        run: |
          cat > Dockerfile <<EOF
          FROM eclipse-temurin:18-jre
          COPY target/*.jar /app/app.jar
          WORKDIR /app
          ENTRYPOINT ["java","-jar","/app/app.jar"]
          EOF

      - name: Limpiar builders antiguos (opcional)
        run: |
          docker buildx rm buildx || echo "No hay builder existente"

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container
          driver-opts:
            - image=moby/buildkit:master

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mydockerhubuser/myapp:${{ github.event.inputs.branch }}
